define yaml anchors - 2

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -182,7 +182,8 @@ jobs:
         name: "— Disk Space —"
         if: always()
         run: df -h /
-      - uses: Jayllyz/free-disk-space@3bda29d61d3f1fa7bf46c5a9a11f22dd20af07c9 # until https://github.com/jlumbroso/free-disk-space/pull/26 # need space for mq broker and image
+      - &free_disk_space
+        uses: Jayllyz/free-disk-space@3bda29d61d3f1fa7bf46c5a9a11f22dd20af07c9 # until https://github.com/jlumbroso/free-disk-space/pull/26 # need space for mq broker and image
         with:
           docker-images: false
       - *df_disk_space
@@ -343,137 +344,101 @@ jobs:
       - *df_disk_space
 
 
-#  test-run-nsides-thresholds-dummy:
-#    if: ${{ github.actor != 'dependabot[bot]' }}  # don't run expensive job when not needed
-#    needs: [ flake8 ]
-#    runs-on: ubuntu-latest
-#    strategy:
-#      # don't fail fast on default branch — so we can rerun just the one job in case of transient failure
-#      fail-fast: ${{ format('refs/heads/{0}', github.event.repository.default_branch) != github.ref }}
-#      matrix:
-#        nsides: [
-#          "1:0",
-#          "1:0 2:12",
-#          "1:0 2:12 4:12"
-#        ]
-#        predictive_scanning_threshold: [
-#          1.0,
-#          0.65,
-#        ]
-#    env:
-#      SKYSCAN_MQ_TOCLIENT_BROKER_ADDRESS: user1@localhost/test
-#      SKYSCAN_MQ_TOCLIENT_AUTH_TOKEN: password  # using this would override password in address
-#      SKYSCAN_MQ_FROMCLIENT_BROKER_ADDRESS: user1@localhost/test
-#      SKYSCAN_MQ_FROMCLIENT_AUTH_TOKEN: password  # using this would override password in address
-#    services:
-#      rabbitmq:
-#        # see image.tag -> https://github.com/Observation-Management-Service/path-kubernetes/blob/main/helm-values-rabbitmq-bitnami.yaml (see https://artifacthub.io/packages/helm/bitnami/rabbitmq/11.14.3)
-#        image: bitnamilegacy/rabbitmq:3.11.15-debian-11-r0
-#        env:
-#          RABBITMQ_USERNAME: user1
-#          RABBITMQ_PASSWORD: password
-#          RABBITMQ_VHOST: test
-#          BITNAMI_DEBUG: true
-#        # Note: `--network` option is not supported.
-#        options: >-
-#          --name rabbitmq
-#          --health-cmd "rabbitmqctl node_health_check"
-#          --health-interval 5s
-#          --health-timeout 5s
-#          --health-retries 10
-#        ports:
-#          - 5672:5672
-#          - 15672:15672
-#    steps:
-#      - name: "— Disk Space —"
-#        if: always()
-#        run: df -h /
-#      - uses: Jayllyz/free-disk-space@3bda29d61d3f1fa7bf46c5a9a11f22dd20af07c9 # until https://github.com/jlumbroso/free-disk-space/pull/26 # need space for mq broker and image
-#        with:
-#          docker-images: false
-#      - name: "— Disk Space —"
-#        if: always()
-#        run: df -h /
-#
-#      - uses: actions/checkout@v5
-#        with:
-#          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
-#          fetch-depth: 0  # setuptools-scm needs to access git tags
-#      - uses: docker/setup-buildx-action@v3
-#      - uses: docker/build-push-action@v6
-#        with:
-#          context: .
-#          file: ./Dockerfile
-#          tags: ${{ env._SCANNER_IMAGE_DOCKER }}
-#          load: true
-#
-#      - name: run
-#        timeout-minutes: 12  # on average max~=8.5min
-#        run: |
-#          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
-#          set -x
-#          source tests/env-vars.sh
-#          export _RECO_ALGO=dummy
-#          export _EVENTS_FILE=$(realpath $REALTIME_EVENTS_DIR/hese_event_01.json)
-#          export _NSIDES="${{ matrix.nsides }}"
-#          export _PREDICTIVE_SCANNING_THRESHOLD=${{ matrix.predictive_scanning_threshold }}
-#
-#          cd ./resources/launch_scripts
-#          python3 local_scan.py $N_WORKERS $CI_TEST_RUN_STDOUT_STDERR_DIR
-#
-#      - name: check no nsides skipped
-#        run: |
-#          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
-#          ls $CI_SKYSCAN_OUTPUT_DIR
-#          # get newest run*.json
-#          export outfile=$(find $CI_SKYSCAN_OUTPUT_DIR -type f -name "run*.json" -exec stat -c '%y %n'  {} + | sort | tail -1 | awk '{print $4}')
-#          echo $outfile
-#          python3 -c '
-#          import json
-#          import os
-#          with open(os.getenv("outfile")) as f:
-#            pydict = json.load(f)
-#          nsides = "${{ matrix.nsides }}"
-#          assert len(pydict) == nsides.count(":")
-#          '
-#
-#      - name: "dump output — central server stdout/stderr"
-#        if: always()
-#        run: |
-#          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
-#          cat $CI_TEST_RUN_STDOUT_STDERR_DIR/server.out
-#      - name: "dump output — worker pilot #1 stdout/stderr"
-#        if: always()
-#        run: |
-#          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
-#          more $CI_TEST_RUN_STDOUT_STDERR_DIR/worker-1/pilot.out | cat
-#      - name: "dump output — worker clients / reco-icetray instances #1 stdouts/stderrs"
-#        if: always()
-#        run: |
-#          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
-#          find $CI_TEST_RUN_STDOUT_STDERR_DIR/worker-1/pilot-* -name "stderrfile" -o -name "stdoutfile" | xargs more | cat
-#          echo "::::::::::::::" && tree $CI_TEST_RUN_STDOUT_STDERR_DIR/worker-1/pilot-*
-#      - name: "dump output — worker pilot #2 stdout/stderr"
-#        if: always() && env.N_WORKERS == '2'
-#        run: |
-#          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
-#          more $CI_TEST_RUN_STDOUT_STDERR_DIR/worker-2/pilot.out | cat
-#      - name: "dump output — worker clients / reco-icetray instances #2 stdouts/stderrs"
-#        if: always() && env.N_WORKERS == '2'
-#        run: |
-#          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
-#          find $CI_TEST_RUN_STDOUT_STDERR_DIR/worker-2/pilot-* -name "stderrfile" -o -name "stdoutfile" | xargs more | cat
-#          echo "::::::::::::::" && tree $CI_TEST_RUN_STDOUT_STDERR_DIR/worker-2/pilot-*
-#
-#      - name: rabbitmq logs
-#        if: always()
-#        run: |
-#          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
-#          docker logs rabbitmq
-#
-#      - name: "— Disk Space —"
-#        if: always()
-#        run: df -h /
+  test-run-nsides-thresholds-dummy:
+    if: ${{ github.actor != 'dependabot[bot]' }}  # don't run expensive job when not needed
+    needs: [ flake8 ]
+    runs-on: ubuntu-latest
+    strategy:
+      # don't fail fast on default branch — so we can rerun just the one job in case of transient failure
+      fail-fast: ${{ format('refs/heads/{0}', github.event.repository.default_branch) != github.ref }}
+      matrix:
+        nsides: [
+          "1:0",
+          "1:0 2:12",
+          "1:0 2:12 4:12"
+        ]
+        predictive_scanning_threshold: [
+          1.0,
+          0.65,
+        ]
+    env:
+      SKYSCAN_MQ_TOCLIENT_BROKER_ADDRESS: user1@localhost/test
+      SKYSCAN_MQ_TOCLIENT_AUTH_TOKEN: password  # using this would override password in address
+      SKYSCAN_MQ_FROMCLIENT_BROKER_ADDRESS: user1@localhost/test
+      SKYSCAN_MQ_FROMCLIENT_AUTH_TOKEN: password  # using this would override password in address
+    services:
+      rabbitmq:
+        # see image.tag -> https://github.com/Observation-Management-Service/path-kubernetes/blob/main/helm-values-rabbitmq-bitnami.yaml (see https://artifacthub.io/packages/helm/bitnami/rabbitmq/11.14.3)
+        image: bitnamilegacy/rabbitmq:3.11.15-debian-11-r0
+        env:
+          RABBITMQ_USERNAME: user1
+          RABBITMQ_PASSWORD: password
+          RABBITMQ_VHOST: test
+          BITNAMI_DEBUG: true
+        # Note: `--network` option is not supported.
+        options: >-
+          --name rabbitmq
+          --health-cmd "rabbitmqctl node_health_check"
+          --health-interval 5s
+          --health-timeout 5s
+          --health-retries 10
+        ports:
+          - 5672:5672
+          - 15672:15672
+    steps:
+      - *df_disk_space
+      - *free_disk_space
+      - *df_disk_space
+
+      - uses: actions/checkout@v5
+        with:
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
+          fetch-depth: 0  # setuptools-scm needs to access git tags
+      - uses: docker/setup-buildx-action@v3
+      - uses: docker/build-push-action@v6
+        with:
+          context: .
+          file: ./Dockerfile
+          tags: ${{ env._SCANNER_IMAGE_DOCKER }}
+          load: true
+
+      - name: run
+        timeout-minutes: 12  # on average max~=8.5min
+        run: |
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+          set -x
+          source tests/env-vars.sh
+          export _RECO_ALGO=dummy
+          export _EVENTS_FILE=$(realpath $REALTIME_EVENTS_DIR/hese_event_01.json)
+          export _NSIDES="${{ matrix.nsides }}"
+          export _PREDICTIVE_SCANNING_THRESHOLD=${{ matrix.predictive_scanning_threshold }}
+
+          cd ./resources/launch_scripts
+          python3 local_scan.py $N_WORKERS $CI_TEST_RUN_STDOUT_STDERR_DIR
+
+      - name: check no nsides skipped
+        run: |
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+          ls $CI_SKYSCAN_OUTPUT_DIR
+          # get newest run*.json
+          export outfile=$(find $CI_SKYSCAN_OUTPUT_DIR -type f -name "run*.json" -exec stat -c '%y %n'  {} + | sort | tail -1 | awk '{print $4}')
+          echo $outfile
+          python3 -c '
+          import json
+          import os
+          with open(os.getenv("outfile")) as f:
+            pydict = json.load(f)
+          nsides = "${{ matrix.nsides }}"
+          assert len(pydict) == nsides.count(":")
+          '
+
+      - *dump_output_central_server
+      - *dump_output_worker_1_pilot
+      - *dump_output_worker_1_clients
+      - *dump_output_worker_2_pilot
+      - *dump_output_worker_2_clients
+      - *dump_rabbitmq_diagnostics
+      - *df_disk_space
 #
 #
 #  test-run-realistic:
