add "splinempe gh-issue reminder timer" - 4

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -492,17 +492,6 @@ jobs:
           - 5672:5672
           - 15672:15672
     steps:
-      - if: matrix.reco_algo == 'splinempe'
-        name: splinempe gh-issue reminder timer
-        run: |
-          start_time="2025-03-18"  # Set the starting date
-          end_time=$(date -d "$start_time +6 months" +%s)
-          current_time=$(date +%s)
-      
-          if [ "$current_time" -ge "$end_time" ]; then
-              echo "::error::it's been six months, how's https://github.com/icecube/skymap_scanner/issues/242 going? Are version-0 result files still being used for splinempe?"
-              exit 1
-          fi
       - uses: jlumbroso/free-disk-space@main  # need space for mq broker and image
         with:
           docker-images: false
@@ -545,6 +534,30 @@ jobs:
           echo $outfile
           cat $outfile
           pip install .  # don't need icecube, so no docker container needed
+          
+          
+          # --------------------------------------------------------------------
+          # splinempe gh-issue reminder timer + special handling
+          if [[ "${{ matrix.reco_algo }}" == "splinempe" ]]; then
+            start_time="2025-03-18"  # Set the starting date
+            end_time=$(date -d "$start_time +6 months" +%s)
+            current_time=$(date +%s)
+            if (( current_time >= end_time )); then
+                echo "::error::it's been six months, how's https://github.com/icecube/skymap_scanner/issues/242 going? Are version-0 result files still being used for splinempe?"
+                exit 1
+            fi
+          
+            python tests/compare_scan_results.py \
+              --actual $outfile \
+              --expected tests/data/results_json/${{ matrix.reco_algo }}/$(basename $outfile) \
+              --assert \
+              --compare-different-versions-ok \
+              || (cat $(ls *.diff.json) && false)
+            exit 0
+          fi
+          # --------------------------------------------------------------------
+          
+          
           python tests/compare_scan_results.py \
             --actual $outfile \
             --expected tests/data/results_json/${{ matrix.reco_algo }}/$(basename $outfile) \
