ci: fix dummy tests

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -256,17 +256,24 @@ jobs:
           export _EVENTS_FILE=$(realpath $REALTIME_EVENTS_DIR/hese_event_01.json)
           export _NSIDES="1:0 2:12 4:12"
           
+          # set special env vars
           if [ "${{ matrix.container_platform }}" == "apptainer" ]; then
               export _RUN_THIS_SIF_IMAGE="$(realpath skymap_scanner.sif)"
               export _EWMS_PILOT_APPTAINER_IMAGE_DIRECTORY_MUST_BE_PRESENT=False
           fi
-          
           if [ "${{ matrix.reco_algo }}" == "crash_dummy" ]; then
               export _SKYSCAN_CI_CRASH_DUMMY_PROBABILITY=0.75
           fi
           
+          # run!
           cd ./resources/launch_scripts
-          python3 local_scan.py $N_WORKERS $CI_TEST_RUN_STDOUT_STDERR_DIR
+          if [ "${{ matrix.reco_algo }}" == "crash_dummy" ]; then
+              set +e  # allow `||` to supress first non-zero exit
+              python3 local_scan.py $N_WORKERS $CI_TEST_RUN_STDOUT_STDERR_DIR \
+                || echo "::warning::scan failed, checking outputs to see if it failed as expected..."
+          else
+              python3 local_scan.py $N_WORKERS $CI_TEST_RUN_STDOUT_STDERR_DIR
+          fi
 
       - if: ${{ matrix.reco_algo == 'crash_dummy' }}
         name: look at stderrfiles
@@ -387,9 +394,7 @@ jobs:
           export _PREDICTIVE_SCANNING_THRESHOLD=${{ matrix.predictive_scanning_threshold }}
 
           cd ./resources/launch_scripts
-          set +e  # allow `||` to supress first non-zero exit
-          python3 local_scan.py $N_WORKERS $CI_TEST_RUN_STDOUT_STDERR_DIR \
-            || echo "::warning::scan failed, checking outputs to see if it failed as expected..."
+          python3 local_scan.py $N_WORKERS $CI_TEST_RUN_STDOUT_STDERR_DIR
 
       - name: check no nsides skipped
         run: |
@@ -441,110 +446,6 @@ jobs:
         run: |
           set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           docker logs rabbitmq
-
-
-  test-run-crash-dummy:
-    needs: [ flake8 ]
-    runs-on: ubuntu-latest
-    env:
-      SKYSCAN_MQ_TOCLIENT_BROKER_ADDRESS: user1@localhost/test
-      SKYSCAN_MQ_TOCLIENT_AUTH_TOKEN: password  # using this would override password in address
-      SKYSCAN_MQ_FROMCLIENT_BROKER_ADDRESS: user1@localhost/test
-      SKYSCAN_MQ_FROMCLIENT_AUTH_TOKEN: password  # using this would override password in address
-      EWMS_PILOT_STOP_LISTENING_ON_TASK_ERROR: False  # we want many crashes
-    services:
-      rabbitmq:
-        # see image.tag -> https://github.com/Observation-Management-Service/path-kubernetes/blob/main/helm-values-rabbitmq-bitnami.yaml (see https://artifacthub.io/packages/helm/bitnami/rabbitmq/11.14.3)
-        image: bitnami/rabbitmq:3.11.15-debian-11-r0
-        env:
-          RABBITMQ_USERNAME: user1
-          RABBITMQ_PASSWORD: password
-          RABBITMQ_VHOST: test
-          BITNAMI_DEBUG: true
-        # Note: `--network` option is not supported.
-        options: >-
-          --name rabbitmq
-          --health-cmd "rabbitmqctl node_health_check"
-          --health-interval 5s
-          --health-timeout 5s
-          --health-retries 10
-        ports:
-          - 5672:5672
-          - 15672:15672
-    steps:
-      - uses: jlumbroso/free-disk-space@main  # need space for mq broker and image
-        with:
-          docker-images: false
-      - uses: actions/checkout@v4
-        with:
-          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
-      - uses: docker/setup-buildx-action@v3
-      - uses: docker/build-push-action@v6
-        with:
-          context: .
-          file: ./Dockerfile
-          tags: ${{ env.CI_DOCKER_IMAGE_TAG }}
-          load: true
-      - name: run
-        timeout-minutes: 12  # on average ~9min
-        run: |
-          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
-          set -x
-          source tests/env-vars.sh
-          export _RECO_ALGO=crash_dummy
-          export _EVENTS_FILE=$(realpath $REALTIME_EVENTS_DIR/hese_event_01.json)
-          export _NSIDES="1:0 2:12 4:12"
-          export _SKYSCAN_CI_CRASH_DUMMY_PROBABILITY=0.75
-          export EWMS_PILOT_TASK_TIMEOUT=15
-
-          cd ./resources/launch_scripts
-          set +e  # allow `||` to supress first non-zero exit
-          python3 local_scan.py $N_WORKERS $CI_TEST_RUN_STDOUT_STDERR_DIR \
-            || echo "::warning::scan failed, checking outputs to see if it failed as expected..."
-      - name: look at stderrfiles
-        run: |
-          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
-          set -x
-          # check for fails/errors
-          
-          error_type_1='intentional crash-dummy error'
-          error_type_2='subprocess timed out after'
-          pattern="$error_type_1|$error_type_2"
-          
-          if find "$CI_TEST_RUN_STDOUT_STDERR_DIR/worker-"*/pilot.out -type f -exec grep -qE "$pattern" {} +; then
-              echo "Match(es) found: PilotSubprocessError and/or TimeoutError occurred."
-          else
-              echo "::error::Could not find the expected error(s) in worker/pilot outputs."
-              exit 1
-          fi
-
-      - name: dump output -- central server stdout/stderr
-        if: always()
-        run: |
-          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
-          cat $CI_TEST_RUN_STDOUT_STDERR_DIR/server.out
-      - name: dump output -- worker pilot \#1 stdout/stderr
-        if: always()
-        run: |
-          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
-          more $CI_TEST_RUN_STDOUT_STDERR_DIR/worker-1/pilot.out | cat
-      - name: dump output -- worker clients / reco-icetray instances \#1 stdouts/stderrs
-        if: always()
-        run: |
-          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
-          find $CI_TEST_RUN_STDOUT_STDERR_DIR/worker-1/pilot-* -name "stderrfile" -o -name "stdoutfile" | xargs more | cat
-          echo "::::::::::::::" && tree $CI_TEST_RUN_STDOUT_STDERR_DIR/worker-1/pilot-*
-      - name: dump output -- worker pilot \#2 stdout/stderr
-        if: always() && env.N_WORKERS == '2'
-        run: |
-          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
-          more $CI_TEST_RUN_STDOUT_STDERR_DIR/worker-2/pilot.out | cat
-      - name: dump output -- worker clients / reco-icetray instances \#2 stdouts/stderrs
-        if: always() && env.N_WORKERS == '2'
-        run: |
-          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
-          find $CI_TEST_RUN_STDOUT_STDERR_DIR/worker-2/pilot-* -name "stderrfile" -o -name "stdoutfile" | xargs more | cat
-          echo "::::::::::::::" && tree $CI_TEST_RUN_STDOUT_STDERR_DIR/worker-2/pilot-*
 
 
   test-run-realistic:
@@ -841,7 +742,6 @@ jobs:
       test-run-dummy,
       test-file-staging,
       test-run-nsides-thresholds-dummy,
-      test-run-crash-dummy,
       test-run-realistic,
       test-run-single-pixel,
     ]
