Add `crash_dummy` Reco (#236) [minor]
Co-authored-by: wipacdevbot <developers@icecube.wisc.edu>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -105,6 +105,7 @@ jobs:
           file: Dockerfile
           tags: icecube/skymap_scanner:local
 
+
   test-build-docker-pulsar:
     needs: test-build-docker
     runs-on: ubuntu-latest
@@ -121,6 +122,7 @@ jobs:
           cache-from: type=gha
           file: Dockerfile_pulsar
           tags: icecube/skymap_scanner:local-pulsar
+
 
   test-run-singularity-dummy-reco:
     needs: test-build-docker
@@ -218,6 +220,7 @@ jobs:
         run: |
           docker logs rabbitmq
 
+
   test-run-nsides-thresholds-dummy:
     needs: test-build-docker
     runs-on: ubuntu-latest
@@ -304,6 +307,62 @@ jobs:
         if: always()
         run: |
           docker logs rabbitmq
+
+
+  test-run-crash-dummy:
+    needs: test-build-docker
+    runs-on: ubuntu-latest
+    env:
+      _CLIENTS_PER_CPU: 1  # there isn't any improvement when >1
+      SKYSCAN_BROKER_ADDRESS: user1@localhost/test
+      SKYSCAN_BROKER_AUTH: password  # using this would override password in address
+    services:
+      rabbitmq:
+        image: bitnami/rabbitmq:latest
+        env:
+          RABBITMQ_USERNAME: user1
+          RABBITMQ_PASSWORD: password
+          RABBITMQ_VHOST: test
+          BITNAMI_DEBUG: true
+        # Note: `--network` option is not supported.
+        options: >-
+          --name rabbitmq
+          --health-cmd "rabbitmqctl node_health_check"
+          --health-interval 5s
+          --health-timeout 5s
+          --health-retries 10
+        ports:
+        - 5672:5672
+        - 15672:15672
+    steps:
+      - uses: actions/checkout@v3
+      - uses: docker/setup-buildx-action@v2
+      - uses: docker/build-push-action@v3
+        with:
+          context: .
+          cache-from: type=gha
+          # cache-to: type=gha,mode=min
+          file: Dockerfile
+          tags: icecube/skymap_scanner:local
+          load: true
+      - name: run
+        run: |
+          set -x
+          source tests/env-vars.sh
+          export _RECO_ALGO=crash_dummy
+          export _EVENTS_FILE=$(realpath $REALTIME_EVENTS_DIR/hese_event_01.json)
+          export _NSIDES="1:0 2:12 4:12"
+          export SKYSCAN_CRASH_DUMMY_PROBABILITY=0.75
+          export EWMS_PILOT_TASK_TIMEOUT=15
+
+          cd ./resources/launch_scripts
+          timeout 240 ./local-scan.sh  || true
+      - name: look at stderrfiles
+        run: |
+          set -x
+          # check for fails
+          find $SKYSCAN_DEBUG_DIR/ -name "stderrfile" -type f -exec sh -c "tail -1 {} | sed -e 's/^.*DEBUG //p' " \; | sort | uniq -c
+
 
   test-run-realistic:
     needs: test-build-docker
@@ -405,6 +464,7 @@ jobs:
         run: |
           docker logs rabbitmq
 
+
   test-file-staging:
     needs: test-build-docker
     runs-on: ubuntu-latest
@@ -424,6 +484,7 @@ jobs:
           docker run --rm -i \
             icecube/skymap_scanner:local \
             python tests/file_staging.py
+
 
   test-run-single-pixel:
     needs: test-build-docker
@@ -532,6 +593,7 @@ jobs:
               test-run-singularity-dummy-reco,
               test-file-staging,
               test-run-nsides-thresholds-dummy,
+              test-run-crash-dummy,
               test-run-realistic,
               test-run-single-pixel
            ]
